spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

  data:
    redis:
      host: jbank-redis
      port: 6379
  #      host: ${SPRING_REDIS_HOST:localhost}
#      port: ${SPRING_REDIS_PORT:6379}
#      password: ${SPRING_REDIS_PASSWORD:}
#      username: ${SPRING_REDIS_USERNAME:}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_EMAIL_USERNAME:}
    password: ${SPRING_EMAIL_PASSWORD:}
    support: ${SUPPORT_EMAIL:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only

security:
  jwt:
    secret-key: ${SECURITY.JWT.SECRET_KEY}
    token-expiration: ${SECURITY.JWT.TOKEN_EXPIRATION}
    refresh-token-expiration: ${SECURITY.JWT.REFRESH_TOKEN_EXPIRATION}

server:
  port: ${SERVER_PORT:8081}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false  # UI только на Gateway, здесь не нужен

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true