scrape_configs:

  - job_name: 'jbank-microservices'
    scrape_interval: 15s
    metrics_path: /actuator/prometheus

    eureka_sd_configs:
      - server: 'http://discovery-service:8761/eureka'

    relabel_configs:
      - source_labels: [__meta_eureka_app_instance_status]
        regex: UP
        action: keep

      - source_labels: [__meta_eureka_app_name]
        target_label: application
        action: lowercase

      - source_labels:
          - __meta_eureka_app_instance_ip_addr
          - __meta_eureka_app_instance_port
        separator: ':'
        target_label: __address__

      - source_labels: [__meta_eureka_app_instance_id]
        target_label: instance_id

  - job_name: 'discovery-service'
    scrape_interval: 15s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['discovery-service:8761']
        labels:
          application: 'discovery-service'