spring:
  application:
    name: transaction-service

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
