spring:
  application:
    name: discovery-service
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
#вопрос