spring:
  application:
    name: admin-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
server:
  port: ${SERVER_PORT:8085}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false