spring:
  application:
    name: admin-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      access: read-only
    metrics:
      access: read-only
    prometheus:
      access: read-only
  tracing:
    export:
      enabled: true
      zipkin:
        enabled: true
        endpoint: http://zipkin:9411/api/v2/spans
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: ${SERVER_PORT:8085}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false