spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8080
