spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service:8081
              predicates:
                - Path=/api/v1/auth/**
                - Path=/api/v1/user/**
              filters:
                - AuthenticationFilter

            - id: account-service
              uri: lb://account-service:8082
              predicates:
                - Path=/api/v1/account/**
              filters:
                - AuthenticationFilter

            - id: admin-service
              uri: lb://admin-service:8085
              predicates:
                - Path=/api/v1/admin/**
              filters:
                - AuthenticationFilter

            - id: card-service
              uri: lb://card-service:8083
              predicates:
                  - Path=/api/v1/cards/**
              filters:
                - AuthenticationFilter

            - id: credit-service
              uri: lb://credit-service:8084
              predicates:
                - Path=/api/v1/credit/**
              filters:
                - AuthenticationFilter

            - id: notification-service
              uri: lb://notification-service:8086
              predicates:
                - Path=/api/v1/notification/**
              filters:
                - AuthenticationFilter

            - id: transaction-service
              uri: lb://transaction-service:8087
              predicates:
                - Path=/api/v1/transaction/**
              filters:
                - AuthenticationFilter

            - id: auth-service-docs
              uri: lb://auth-service:8081
              predicates:
                - Path=/auth-docs/**
              filters:
                - RewritePath=/auth-docs/(?<segment>.*), /$\{segment}

            - id: account-service-docs
              uri: lb://account-service:8082
              predicates:
                - Path=/account-docs/**
              filters:
                - RewritePath=/account-docs/(?<segment>.*), /$\{segment}

            - id: admin-service-docs
              uri: lb://admin-service:8085
              predicates:
                - Path=/admin-docs/**
              filters:
                - RewritePath=/admin-docs/(?<segment>.*), /$\{segment}

            - id: card-service-docs
              uri: lb://card-service:8083
              predicates:
                - Path=/card-docs/**
              filters:
                - RewritePath=/card-docs/(?<segment>.*), /$\{segment}

            - id: credit-service-docs
              uri: lb://credit-service:8084
              predicates:
                - Path=/credit-docs/**
              filters:
                - RewritePath=/credit-docs/(?<segment>.*), /$\{segment}

            - id: transaction-service-docs
              uri: lb://transaction-service:8087
              predicates:
                - Path=/transaction-docs/**
              filters:
                - RewritePath=/transaction-docs/(?<segment>.*), /$\{segment}

            - id: notification-service-docs
              uri: lb://notification-service:8086
              predicates:
                - Path=/notification-docs/**
              filters:
                - RewritePath=/notification-docs/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      access: read-only
    metrics:
      access: read-only
    prometheus:
      access: read-only
  tracing:
    export:
      enabled: true
      zipkin:
        enabled: true
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
    sampling:
      probability: 1.0

security:
  jwt:
    secret-key: ${SECURITY.JWT.SECRET_KEY}

server:
  port: ${SERVER_PORT:8086}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth-docs/v3/api-docs
      - name: Account Service
        url: /account-docs/v3/api-docs
      - name: Admin Service
        url: /admin-docs/v3/api-docs
      - name: Credit Service
        url: /credit-docs/v3/api-docs
      - name: Card Service
        url: /card-docs/v3/api-docs
      - name: Notification Service
        url: /notification-docs/v3/api-docs
      - name: Transaction Service
        url: /transaction-docs/v3/api-docs
    urls-primary-name: Auth Service

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG