spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service:8081
              predicates:
                - Path=/api/v1/auth/**, /api/v1/user/**
              filters:
                - AuthenticationFilter

            - id: account-service
              uri: lb://account-service:8082
              predicates:
                - Path=/api/v1/account/**
              filters:
                - AuthenticationFilter

            - id: admin-service
              uri: lb://admin-service:8085
              predicates:
                - Path=/api/v1/admin
              filters:
                - AuthenticationFilter

            - id: card-service
              uri: lb://card-service:8083
              predicates:
                  - Path=/api/v1/cards
              filters:
                - AuthenticationFilter

            - id: credit-service
              uri: lb://credit-service:8084
              predicates:
                - Path=/api/v1/credit
              filters:
                - AuthenticationFilter

            - id: auth-service-docs
              uri: lb://auth-service-docs:8081
              predicates:
                - Path=/auth-docs/**
              filters:
                - RewritePath=/auth-docs/(?<segment>.*), /$\{segment}

            - id: account-service-docs
              uri: lb://account-service-docs:8082
              predicates:
                - Path=/account-docs/**
              filters:
                - RewritePath=/account-docs/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret-key: ${SECURITY.JWT.SECRET_KEY}

server:
  port: 8086

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth-docs/v3/api-docs
      - name: Account Service
        url: /account-docs/v3/api-docs
    urls-primary-name: Auth Service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG