spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/**
          filters:
            - AuthenticationFilter

        - id: account-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/account/**
          filters:
            - AuthenticationFilter

        - id: auth-service-docs
          uri: http://localhost:8081
          predicates:
            - Path=/auth-docs/**
          filters:
            - RewritePath=/auth-docs/(?<segment>.*), /${segment}

        - id: account-service-docs
          uri: http://localhost:8080
          predicates:
            - Path=/account-docs/**
          filters:
            - RewritePath=/account-docs/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${SECURITY.JWT.SECRET_KEY}

server:
  port: 8083

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /auth-docs/v3/api-docs
      - name: account-service
        url: /account-docs/v3/api-docs
      - name: gateway
        url: /v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
